#!/usr/bin/env bash
# Generate the low-level Pydantic model layer from the vendored OpenAPI spec.
#
# Input : spec/client.yaml  (vendored from the platform repo; see spec/SOURCE.md)
# Output: src/lunogram/gen/models.py  (committed; "DO NOT EDIT" header)
#
# This is the single source of truth for codegen flags. It is invoked by the
# `make generate` target and by CI. Requires datamodel-code-generator (pinned in
# the project's `dev` extra) on a Python 3.10+ interpreter.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

datamodel-codegen \
  --input spec/client.yaml \
  --input-file-type openapi \
  --output src/lunogram/gen/models.py \
  --output-model-type pydantic_v2.BaseModel \
  --target-python-version 3.10 \
  --use-standard-collections \
  --use-union-operator \
  --snake-case-field \
  --use-schema-description \
  --use-field-description \
  --field-constraints \
  --disable-timestamp \
  --custom-file-header "# generated by datamodel-codegen; DO NOT EDIT.
# source: spec/client.yaml  (run \`make generate\` to regenerate)"

echo "Generated src/lunogram/gen/models.py from spec/client.yaml"
